### ISSUE TITLE
Add Link Archiving

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#102]
I'd like to add a feature that takes all links that are verified to be active and add them to the Internet Archive Wayback Machine to preserve them in time. There is a draft python script in lib called archive.py. The idea is that you navigate to https://web.archive.org/save/{url} the service automatically archives that page. So after verifying that it returns a valid code, we would just connect to all of those sites and it would create a snapshot. I'd love for this to be an optional argument like -a or something. This way it is optional and we don't take more resources than we need. Anyone able to complete this task, please take a stab at it.

**Comment by marshalmiller** [comment]
Another Option Could be to use this Library. https://github.com/oduwsdl/archivenow

**Comment by rachaelcrook** [comment]
@marshalmiller Can you please assign this to me?

**Comment by marshalmiller** [comment]
@rachaelcrook, It's all yours. Thank you for your interest in helping our project.

**Comment by marshalmiller** [comment]
@rachaelcrook, are you still working on this issue? I don't want to undermine any work or progress you have made on it, but I would open it up if you could not get to it. Either way, thank you for your interest in helping out our project.

**Comment by mailtodanish** [comment]
I will work on this.

**Comment by marshalmiller** [comment]
Resolved in PR #150 by the very generous @mailtodanish
