### ISSUE TITLE
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 55, column 10

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#123]
Receive this error when I run the file. Traceback below. File Attached.

> Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\linkrot.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\linkrot\cli.py", line 182, in main
    pdf = linkrot.linkrot(args.pdf)
  File "c:\python38\lib\site-packages\linkrot\__init__.py", line 131, in __init__
    self.reader = PDFMinerBackend(self.stream)
  File "c:\python38\lib\site-packages\linkrot\backends.py", line 213, in __init__
    self.metadata.update(xmp_to_dict(metadata))
  File "c:\python38\lib\site-packages\linkrot\libs\xmp.py", line 92, in xmp_to_dict
    return XmpParser(xmp).meta
  File "c:\python38\lib\site-packages\linkrot\libs\xmp.py", line 41, in __init__
    self.tree = ET.XML(xmp)
  File "c:\python38\lib\xml\etree\ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 55, column 10

[ah-5.pdf](https://github.com/marshalmiller/linkrot/files/9222585/ah-5.pdf)

**Comment by marshalmiller** [comment]
Appears to be an XML issue.

**Comment by marshalmiller** [comment]
The issue appears that some metadata starts with a number, which is not allowed. So I think the best way to resolve this issue would be to pass an argument to the XML parser library to ignore invalid tags and drop them.

Does anyone have any ideas on how to accomplish this?

**Comment by wiseaidev** [comment]
After a little investigation, It turns out that the following tag was causing the issue:

```sh
<6U7vcnMyNmwuOmd2GmgqLyLNNz.eLlt7_y.eGz9f-m.j7zd2QntaOo9ePnt6JmtmPmM-Tma/>
```

```python
>>> ET.XML('<6U7vcnMyNmwuOmd2GmgqLyLNNz.eLlt7_y.eGz9f-m.j7zd2QntaOo9ePnt6JmtmPmM-Tma/>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harmouch/.pyenv/versions/3.9.10/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
```

I am not sure how to tell the built-in `xml` library to escape it, probably it is not possible:

```python
>>> help(ET.XML)
XML(text, parser=None)
```

I tried different parsers, unfortunately it didn't work:

```sh
>>> ET.XML(xmp, ET.XMLParser(encoding="utf-8"))
``` 

A possible solution is to migrate to [lxml](https://lxml.de/). I will investigate this issue further and try to solve it.

**Comment by wiseaidev** [comment]
Solved the issue, but it requires merging [this PR first](https://github.com/marshalmiller/linkrot/pull/149) because I want to add `lxml` as a new dependency in the `pyproject.toml` file rather than in the old `requirements.txt` file. Once done, ping me to open a new PR.

**Comment by marshalmiller** [comment]
@wiseaidev How would you feel about me merging it to a new branch until I have time to fully review the new structure? I'm sure you are correct, but I want to read more about the new process before merging it with the main branch.

**Comment by wiseaidev** [comment]
Alright, sounds logical. Now I will open a PR based on the old project structure to solve this issue. Then I will open another PR to update the `pyproject,toml` file after the merge into the main branch.

**Comment by marshalmiller** [comment]
@wiseaidev do we still need the xml.etree now that we are using lxml? Just curious

**Comment by wiseaidev** [comment]
Removing `xml.etree` would introduce a lot of changes since `find` and `findall` are not available in `lxml`.

**Comment by marshalmiller** [comment]
Perfect. Just checking. Thank you.

**Comment by marshalmiller** [comment]
@wiseaidev I have merged pyproject into the main branch. I'm going to reopen this just as a reminder for the XML fix.

**Comment by marshalmiller** [comment]
Addressed in PR #158

**Comment by tomhandley** [comment]
In case anyone else has a similar issue, I found the ampersand character (&) can cause this error too.

**Comment by marshalmiller** [comment]
@tomhandley does the & affect the lxml as well? Or just the original usage of xml?
