### ISSUE TITLE
Add DOIs to References Summary 

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#128]
It would be nice to display the number of DOIs in the References Summary section with URLs and PDFs.

**Comment by mailtodanish** [comment]
@marshalmiller  I will work on this. Could you please explain more by example.

**Comment by marshalmiller** [comment]
@mailtodanish Certainly. Not my best description. You previously had a screenshot in your post. If you look at the results, it says References: 6, and then under it says URLs: 6. If it detects PDFs, it added PDFs: # under that. And so on. I would like to add that number under that section. So, if I can refer back to that screenshot, it would be DOIs: 4. I say for because dx.doi would not resolve. Does that make sense? I can try to give my own screenshot if that would help.

PS. Thank you again for your help on both of these projects. It's very encouraging to see contributions.

**Comment by mailtodanish** [comment]
@marshalmiller  please provide me a sample pdf with doi. sample folder has number of pdf but I am not able to get pdf with doi.

**Comment by marshalmiller** [comment]
This one has a few. I hope this helps. Let me know if you need anything else. Thank you again for your help. 
[ss-491.pdf](https://github.com/marshalmiller/linkrot/files/9690742/ss-491.pdf)

**Comment by mailtodanish** [comment]
@marshalmiller  below output looks okay ?
![image](https://user-images.githubusercontent.com/7193460/193420580-97adba58-6370-4647-8f20-44ca0d0649cf.png)

**Comment by marshalmiller** [comment]
@mailtodanish It looks good. But I would like it to still include the DOIs in the URL count since DOIs are still URLs. And URLs should probably be the first item too just since it's a wider net.

**Comment by mailtodanish** [comment]
@marshalmiller  Is it okay?
![image](https://user-images.githubusercontent.com/7193460/193421412-5e9535ba-9498-4454-a4cf-e8ef29cefda7.png)

**Comment by marshalmiller** [comment]
@mailtodanish Perfect! Thank you.

**Comment by marshalmiller** [comment]
Addressed in PR #144 thanks to @mailtodanish.
