### ISSUE TITLE
Remove Python 2 checks and functionality.

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#130]
Keeping support for Python 2 might be slowing down some of the process. Of more concern is that in order to patch vulnerabilities that exist in some libraries Python 2 depends on, we have had to cut support for some versions of Python 3. Specifically 3.6,3.7.  3.7 is still fairly widely used and I think I'd prefer to remove Python 2 support and bring back 3.7. Even though it's clearly a bigger task.

**Comment by astitvaveergarg** [comment]
Hi There, Incan Work on this issue

**Comment by astitvaveergarg** [comment]
Thanks for Assigning me This Issue, I would Like To get a Overall Idea about What you Actually need, As In your Code, you have Specified only 3 requirements and 7 dev requirements, So please help me understand that.

**Comment by marshalmiller** [comment]
Dev requirements are only used for CI/CD purposes, like linting, checking for vulnerabilities, and running tests. They are not used with the actual program. Only the requirements file is installed. I believe the only requirement that is solely for Python 2 is numpy.

**Comment by westofwest** [comment]
@marshalmiller I would like to work on this issue, if you don't mind. https://adamj.eu/tech/2019/03/13/dropping-python-2-support/ would this be a good guideline on how to handle this issue.

**Comment by marshalmiller** [comment]
@westofwest It's all yours. Thank you for your help.

**Comment by westofwest** [comment]
@marshalmiller I am working on removing python2 support, but am unsure on how to bring back 3.7 support. Could you shine a light on how to do so?

**Comment by marshalmiller** [comment]
@westofwest Oh sorry. I think only I can bring back support for 3.7. There is a conflict with dependencies that made it impossible to keep Python 2 and 3.7. So if you just submit the PR that has Python 2 appropriately removed, I can add 3.7 back.

**Comment by marshalmiller** [comment]
Resolved thanks to the work of @westofwest in PR #140

**Comment by marshalmiller** [comment]
@westofwest just to follow up. Python 3.7 has been added again. Thank you for your work.

**Comment by westofwest** [comment]
No problem! Happy to help.
