### ISSUE TITLE
Move from `requirements.txt`, `requirements_dev.txt`, `setup.cfg`, and `setup.py` to `pyproject.toml`.

### ISSUE THREAD

**Issue by wiseaidev** [marshalmiller/linkrot#148]
**Is your feature request related to a problem? Please describe.**
Hey @marshalmiller. As you may already know, the use of `setup.cfg`, `setup.py`, and `requirements.txt` files is quite [outdated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). Because of [PEP 517](https://peps.python.org/pep-0517/), [PEP 660](https://peps.python.org/pep-0660/), and [PEP 631](https://peps.python.org/pep-0631/), the packaging is now being standardized on the usage of the `pyproject.toml` file.

**Describe the solution you'd like**
Given the above info, the project packaging should add support for `pyproject.toml`.

**Describe alternatives you've considered**
Not available.

**Additional context**
That's pretty much it. What do you think? Also, I would like to work on this issue.

**Comment by marshalmiller** [comment]
@wiseaidev Thank you. I'm fairly basic, so I didn't realize these were outdated methods. Let me read up on everything and review your PR. I appreciate you trying to streamline our project.

**Comment by wiseaidev** [comment]
Hey @marshalmiller, thanks for the response. One thing left, I have noticed that the repo is quite heavy because of the [`Random Pdf Samples`](https://github.com/marshalmiller/linkrot/tree/main/Random%20PDF%20Samples). Therefore, I would also suggest moving this folder into any cloud storage bucket available out there and adding a link to that bucket in the readme file. This way, the repo will contain only code.

**Comment by marshalmiller** [comment]
@wiseaidev this is a great idea. Would you mind opening a separate issue about this? Thank you for improving our project.

**Comment by wiseaidev** [comment]
Alright. I am going to open a separate issue and work on it.

**Comment by harsh098** [comment]
May I work on the issue ?

**Comment by marshalmiller** [comment]
@harsh098 This issue has already been addressed by @wiseaidev in PR #149. Thank you for your interest. It remains open simply because I have yet to merge it with the main branch. I do appreciate your willingness to help.

**Comment by marshalmiller** [comment]
@wiseaidev this is officially merged into the main branch. Would you mind resubmitting the XML fix? Sorry, it took so long. Also. How do I set the version number in this new structure? I used to use setup.py, and I see the dynamic tag, but I'm not positive how to use that. Any help would be appreciated.
