### ISSUE TITLE
Separate code from data

### ISSUE THREAD

**Issue by wiseaidev** [marshalmiller/linkrot#152]
**Is your feature request related to a problem? Please describe.**

The current size of the repo is too big because of pdf data samples:

```sh
➜  du -sh * | sort -h
4.0K	CONTRIBUTING.md
4.0K	LICENSE
4.0K	Makefile
4.0K	pyproject.toml
4.0K	SECURITY.md
8.0K	code_of_conduct.md
8.0K	README.md
44K	branding
68K	linkrot
1.7M	tests
919M	Random PDF Samples
``` 

**Describe the solution you'd like**
I suggest either storing the pdf files in a separate repo or on a cloud provider's bucket.

**Describe alternatives you've considered**
Not available.

**Additional context**
That's pretty much. I am currently working on this issue.

**Comment by wiseaidev** [comment]
This [tests/pdfs](https://github.com/marshalmiller/linkrot/tree/main/tests/pdfs) should also be removed. For `pytest` to run successfully, we can use the setup teardown approach. Download the pdfs using [mega.py](https://github.com/odwyersoftware/mega.py), and once the tests finishes, we can delete the files. This can be done using `pytest.fixture`:

```python
import pytest
from mega import Mega

@pytest.fixture(scope='module')
def download_pdfs():
    print('*****SETUP*****')
    # mega client
    mega = Mega()
    m = mega.login()
    file = m.download_url("mega.nz url", "./tests")
    yield
    # Delete files after tests finished
    print('******TEARDOWN******')

def test_linkrot_utils(download_pdfs):
    # Do some testing.
```

**Comment by wiseaidev** [comment]
Hey @marshalmiller, these PRs are ready for reviews. Now the repo contains only code.

**Comment by wiseaidev** [comment]
```sh
➜  du -sh * | sort -h
4.0K	CONTRIBUTING.md
4.0K	LICENSE
4.0K	Makefile
4.0K	pyproject.toml
4.0K	SECURITY.md
8.0K	code_of_conduct.md
8.0K	README.md
44K	branding
48K	tests
68K	linkrot
```

**Comment by marshalmiller** [comment]
@wiseaidev thank you for helping us streamline this project.
