### ISSUE TITLE
Run code formatter

### ISSUE THREAD

**Issue by marwansalem** [marshalmiller/linkrot#162]
When I ran the code formatter (black), a number of files were affected.
The files are:
* __init__.py
* archive.py
* backends.py
* cli.py
* colorprint.py
* downloader.py
* extractor.py
* threadpool.py
* xmp.py

**Comment by marshalmiller** [comment]
@marwansalem thank you for checking on this. We automatically run a linter and formatter after every pull request or merge. Unfortunately, with so many changes happening simultaneously, it is hard to keep up. We will address the format and style of the code once Hacktoberfest is over. If you'd like to check out what we do, I invite you to check out our GitHub action which runs these checks. Thank you for trying to make our project better.

https://github.com/marshalmiller/linkrot/blob/main/.github/workflows/lint-and-test.yml
