### ISSUE TITLE
Add Comments to cli.py

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#18]
Add comments to make it more organized and accessible to others.

**Comment by Kartik-byte** [comment]
Hey, Can I work on this ?

**Comment by vacom13** [comment]
@marshalmiller I was thinking that maybe I could take up this as well and the other one? Just finish them off.

**Comment by marshalmiller** [comment]
@vacom13 It has been over a month since any communication. I will add you to both issues. Thank you for your help.

**Comment by vacom13** [comment]
@marshalmiller Sorry for the delay I have been busy with some stuff so didnt get a chance 😅. I will complete it asap.
