### ISSUE TITLE
Add Comments to colorprint.py

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#19]
Add comments to make it more organized and accessible to others.

**Comment by Kishore-abhimanyu** [comment]
Can i take this issue?

**Comment by vacom13** [comment]
@marshalmiller have the comments been added or this still needs work? Cus I will take it up then?

**Comment by marshalmiller** [comment]
I have not received any pull requests for it yet. Go ahead and run with it.

**Comment by vacom13** [comment]
Sure. Great. Will try to add asap and as much as I can. Though please do guide me wherever needed. 😅

**Comment by vacom13** [comment]
@marshalmiller Hi. I get that the function is basically just formatting the text using those values. I am not sure what they are called. I suppose ANSI escape sequences? For some reason, I am having a hard time finding some good explanation for `__future__` module. Could you explain in brief the point or point me towards something useful?

**Comment by marshalmiller** [comment]
A future statement is a directive to the compiler that a particular module should be compiled using syntax or semantics that will be available in a specified future release of Python. The future statement is intended to ease migration to future versions of Python that introduce incompatible changes to the language. It allows the use of the new features on a per-module basis before the release in which the feature becomes standard.

AKA - it's actually setting up a future import. In this case, it's not actually a module. It's like a pre-loader. Does that make any sense?

**Comment by vacom13** [comment]
Yeah it does make sense. Thank you. I should be done with this today!

**Comment by vacom13** [comment]
I created the pr @marshalmiller . Not sure if its enough. Do tell me if more needs to be added!

**Comment by marshalmiller** [comment]
Addressed in PR #56. Thank you @vacom13 for contributing to the project.
