### ISSUE TITLE
Add Comments to exceptions.py

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#21]
Add comments to make it more organized and accessible to others.

**Comment by DevPriSha** [comment]
may I pick this issue up?

**Comment by DevPriSha** [comment]
I saw the file and it only had a bunch of docstrings for classes. I am confused on what comments can be added since there aren't any operations performed.

**Comment by marshalmiller** [comment]
You are correct. Sorry about that. I was just adding all of the .py files. Thank you for reporting back. Would you like to take Issue #17 instead?

**Comment by DevPriSha** [comment]
sure. Thankyou

**Comment by marshalmiller** [comment]
Awesome! Thank you. I need you to comment on the issue in order for me to assign it to you. Thank you.
