### ISSUE TITLE
Add Comments to extractor.py

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#22]
Add comments to make it more organized and accessible to others.

**Comment by hmajid2301** [comment]
I can pick this up.

**Comment by hmajid2301** [comment]
I think you may also have to tag your repo with hacktoberfest for it to be accepted by them ?

**Comment by marshalmiller** [comment]
Yes. You are correct. I just did this so you should receive credit toward your count. Please let me know if you do not and I will address the issue. Thank you.
