### ISSUE TITLE
Add Comments to setup.py

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#23]
Add comments to make it more organized and accessible to others.

**Comment by hmajid2301** [comment]
i can pick this up.

**Comment by hmajid2301** [comment]
I notice setup.py already has a lot of comments. What kind off comments would you like me to add ?

**Comment by marshalmiller** [comment]
You are correct. I apologize. I must have included this file by mistake. I'm sorry. I will close this issue. Feel free to pick up another one with comments to do. Thank you for your help and appropriate response.
