### ISSUE TITLE
(Bug)

### ISSUE THREAD

**Issue by ghost** [marshalmiller/linkrot#234]

**Comment by marshalmiller** [comment]
>I just installed linkrot on my Windows 11 PC, and without any errors.
When I try to use it with some of my PDF's (Academic Journal Articles), it just give an error code.

> C:\Users\fn31>linkrot Abal.pdf
ERROR 4: Invalid PDF (TextConverter.init() got an unexpected keyword argument 'codec')
> C:\Users\fn31>linkrot ABasicStudy.pdf
ERROR 4: Invalid PDF (TextConverter.init() got an unexpected keyword argument 'codec')

@MrUnknown789556 Can you explain how you addressed the issue? Just in case someone else runs into this issue in the future?

**Comment by ghost** [comment]
> > I just installed linkrot on my Windows 11 PC, and without any errors.
> > When I try to use it with some of my PDF's (Academic Journal Articles), it just give an error code.
> 
> > C:\Users\fn31>linkrot Abal.pdf
> > ERROR 4: Invalid PDF (TextConverter.init() got an unexpected keyword argument 'codec')
> > C:\Users\fn31>linkrot ABasicStudy.pdf
> > ERROR 4: Invalid PDF (TextConverter.init() got an unexpected keyword argument 'codec')
> 
> @MrUnknown789556 Can you explain how you addressed the issue? Just in case someone else runs into this issue in the future?

Today I uninstalled the linkrot package, and then installed it again. Now it works splendid (extracted all references correctly). I think the problem originally was due to older other packages I have downloaded in time which gave the problem (I have updated since).

**Comment by marshalmiller** [comment]
@MrUnknown789556 Awesome. Thanks. Just wanted to check. I appreciate the follow-up.
