### ISSUE TITLE
(Update) documentation for python library usage

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/linkrot#27]
The main documentation needs to be updated to include the usage of linkrot as a python library as well. Some of it can be found in the docstrings of this [file](https://github.com/marshalmiller/linkrot/blob/main/linkrot/__init__.py).

**Comment by marshalmiller** [comment]
@aditirao7 Thank you. I will address this issue ASAP.

**Comment by marshalmiller** [comment]
@aditirao7 Would you mind taking this task? I just think it will be better and more accurate coming from you as you've implemented it so well. If not, that's fine. You've done so much already.

**Comment by aditirao7** [comment]
Okay, I'll take this up

**Comment by marshalmiller** [comment]
@aditirao7 Thank you so much!
