### ISSUE TITLE
(Bug) AttributeError: 'NoneType' object has no attribute 'findall'

### ISSUE THREAD

**Issue by aditirao7** [marshalmiller/linkrot#45]
**Describe the bug**
Certain PDFs give Attribute Error 

**To Reproduce**
1. Download [Research_Ethics.pdf](https://github.com/marshalmiller/linkrot/files/7332249/Research_Ethics.pdf)
2. Open terminal and run:
```bash
linkrot <path_to_above_file>
```

**Expected behavior**
It should generate the expected linkrot report.

**Screenshots**
![Screenshot from 2021-10-12 23-37-47](https://user-images.githubusercontent.com/57457307/137007189-a06627e3-9110-4f80-914e-845a7ea14f85.png)

**Comment by bridyash13** [comment]
Hey could you please assign this issue to me

**Comment by rosdyana** [comment]
@marshalmiller Do you think it's valid metadata?

`b"<?xpacket begin='' id='W5M0MpCehiHzreSzNTczkc9d' bytes='1094'?><rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'><rdf:Description about='' xmlns='http://ns.adobe.com/pdf/1.3/' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:CreationDate='2003-07-16T21:26:49Z' pdf:ModDate='2003-07-16T21:26:49Z' pdf:Producer='http://createpdf.adobe.com V5.5' pdf:Author='www' pdf:Creator='PScript5.dll Version 5.2' pdf:Title='Microsoft Word - 3F15C48F-2C4A-189D45.doc'/>\n<rdf:Description about='' xmlns='http://ns.adobe.com/xap/1.0/' xmlns:xap='http://ns.adobe.com/xap/1.0/' 
xap:CreateDate='2003-07-16T21:26:49Z' xap:ModifyDate='2003-07-16T21:26:49Z' xap:Author='www' xap:MetadataDate='2003-07-16T21:26:49Z'><xap:Title><rdf:Alt><rdf:li xml:lang='x-default'>Microsoft Word - 3F15C48F-2C4A-189D45.doc</rdf:li></rdf:Alt></xap:Title></rdf:Description>\n<rdf:Description about='' xmlns='http://purl.org/dc/elements/1.1/' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:creator='www' dc:title='Microsoft Word - 3F15C48F-2C4A-189D45.doc'/>\n</rdf:RDF><?xpacket end='r'?>\n"`

We can avoid this issue by adding try-catch or checking if the metadata is parseable by the XMP library.
What do you think?

**Comment by marshalmiller** [comment]
@rosdyana I think this may have worked. The issue is now that since we no longer receive this error, the program continues to run and times out. Which is a different issue we are looking at (#36). I will reopen this if the error shows up again, but for now, I consider this solved.

**Comment by marshalmiller** [comment]
This update does not appear to have worked upon further review. I have updated the code and the new 2.3 version in pip is updated. Let me know if it is working for you.

**Comment by rosdyana** [comment]
@marshalmiller looks good to me, I have installed version 2.3 from PIP and it works. Could you please tell me which part that is not worked as expected?

**Comment by marshalmiller** [comment]
@rosdyana You're right. I'm sorry. My mind has clearly been lost. It does work perfectly. I updated it on the wrong machine. All fixed. You did awesomely. I apologize for my confusion. I greatly appreciate your willingness to help.

**Comment by rosdyana** [comment]
@marshalmiller no worries, glad to hear that. Let me know if you need any. Cheers!
