### ISSUE TITLE
Timeout Issues

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#53]
With Larger files or more pages, the process times out too quickly and does not complete.

**Comment by abhishekp-uc** [comment]
Could you provide a working example for which this is occurring and more details on how quickly it times out? @marshalmiller

**Comment by marshalmiller** [comment]
I apologize, @abhishekp-uc. It appears like the issue and symptoms I was seeing were coming from elsewhere. Thank you for your interest in helping.
