### ISSUE TITLE
Detect Embeded URLs.

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#62]
I'd love to add the ability to detect URLs that are embedded (hyperlinked) in the PDF.

**Comment by marshalmiller** [comment]
This is the worst idea I've ever heard.

**Comment by marshalmiller** [comment]
This is shit

**Comment by chehe040** [comment]
Hey, I would like to work on this issue.

**Comment by marshalmiller** [comment]
It's all yours, @chehe040. Thank you for your interest in helping.

**Comment by marwansalem** [comment]
I was eyeing this one for a while! :D

**Comment by marshalmiller** [comment]
@marwansalem feel free to take a crack at it, but if @chehe040 can solve it, I have to give them priority.

**Comment by marwansalem** [comment]
Great, then I'd like to verify what do you mean by embedded URLs, because hyperlinks are already supported. Or do you means links embedded in other elements like images?

I have also checked hyperlinks on images, they are supported as well

**Comment by marshalmiller** [comment]
@marwansalem you are correct. I'm going to be honest, this issue is from a very early version of the program. At some point, I must have already addressed this. Thank you for bringing this up. I did not know about the image links. That's very useful. Thank you @chehe040 for your willingness to help out, but it appears like this is no longer an issue. Thank you both for helping out with our project.

**Comment by marwansalem** [comment]
@chehe040 or I can add a test case for it what do you think? 


I believe the :mailto issue was a side effect from supporting embedded URLs

**Comment by marshalmiller** [comment]
Works for me. Anything to enhance the project. Tests are always helpful. Can you create an issue for it so I can assign it to you?

**Comment by marwansalem** [comment]
Great

**Comment by marwansalem** [comment]
#160

**Comment by marwansalem** [comment]
There's something worth mentioning

if you have a link like [github.com/marshalmiller/linkrot](https://github.com/marshalmiller/linkrot)
Both `github.com/marshalmiller/linkrot` & `https://github.com/marshalmiller/linkrot` will be shown as references.
Are you okay with something like this?
