### ISSUE TITLE
Displays Page Number Wrong in Results

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#69]
When it returns the results of links that it tests, it gives a list of the links, along with a page number. The page number would appear to be the page the link was found on but it is actually just the total number of pages in the PDF. It would be extremely helpful if we could get it to display the correct page number.

**Comment by mailtodanish** [comment]
@marshalmiller  you mean under "PDF References"? if possible please add an image and description that will be helpful.

**Comment by marshalmiller** [comment]
@mailtodanish thank you for your interest. I have attached an image. As you can see, it lists the broken links on page 23 of the document. None of the links are on that page. There are actually only 23 pages in the doc. 

![Screenshot 2022-09-27 141540](https://user-images.githubusercontent.com/30907840/192605359-a8449576-267d-4777-8a30-85c2dc466a0c.png)

**Comment by huyszn** [comment]
@marshalmiller Which pdf file was used to get that summary? I want to see if my potential solution is correct.

**Comment by marshalmiller** [comment]
@huyszn, thank you for your interest in helping. @ajratnam submitted PR #147, which resolved the issue. Thank you both for your willingness to contribute.
